### ISSUE TITLE
Support for ARM-based servers?

### ISSUE THREAD

**Issue by knuxify** [cheehoong/asustor-apk-pihole#2]
Could you please add support for ARM-based servers? The package seems to work fine on my AS3302T after changing "architecture" to "any" in the config.json.

**Comment by cheehoong** [comment]
I have make this change to "any". not sure will able to pass the ADM development security check. finger cross.
Last year I not able to pass it. because I do not have ARM base machine to test.

**Comment by cheehoong** [comment]
Can you check, are you using docker-ce (>=20.10.2.r2)"?

**Comment by knuxify** [comment]
I'm on docker-ce 20.10.17.r1:

![image](https://user-images.githubusercontent.com/23167991/210719756-736ea612-0b99-43e5-bf3c-e9444c5e9e54.png)

**Comment by cheehoong** [comment]
added support for arm64.
